system: "base16"
name: "Gruvbox Dark, Hard"
author: "Dawid Kurek (dawikur@gmail.com), morhetz (https://github.com/morhetz/gruvbox)"
variant: "dark"
palette:
  base00: "#282828" # ----
  base01: "#3c3836" # ---
  base02: "#504945" # --
  base03: "#665c54" # -
  base04: "#928374" # +
  base05: "#a89984" # ++
  base06: "#ebdbb2" # +++
  base07: "#fbf1c7" # ++++
  base08: "#cc241d" # red
  base09: "#d79921" # orange
  base0A: "#fabd2f" # yellow
  base0B: "#b8bb26" # green
  base0C: "#8ec07c" # aqua/cyan
  base0D: "#83a598" # blue
  base0E: "#b16286" # purple
  base0F: "#d65d0e" # brown
